name: Run Selenium tests

on:
#   schedule:
#     - cron: '0 5 * * 1-5'
  push:
    branches:
      - "feature/github-actions"
  pull_request:
    branches:
      - "main"

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest
    container: cimg/openjdk:11.0
    env:
      MAVEN_OPTS: -Xmx3200m
      DISPLAY: :99
    steps:
      # Checkout the code as the first step.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install latest version of Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |   sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable
      - name: Use ChromeDriver found in repository
        run: |
          sudo chmod 777 /home/circleci/circleCiTesting/resources/windows/chromedriver.exe
          sudo apt-get install libxi6 libgconf-2-4
          sudo apt-get -y install xvfb gtk2-engines-pixbuf
          sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
          sudo apt-get install xvfb
          sudo apt-get -y install imagemagick x11-apps
      - name: Running X virtual framebuffer
        run: |
           Xvfb :0 -ac &
    #   - name: Run Tests
    #     run: |
    #       export DISPLAY=:99
        # - save_cache:
        #     paths:
        #       - ~/.m2
        #     key: v1-dependencies-{{ checksum "pom.xml" }}
          
        # run tests!
      - name: Run Tests
        run: |
          mvn test